pkg/media/engine.go
pkg/media/engine_test.go
pkg/rtc/transport/webrtctransport.go
pkg/rtc/transport/webrtctransport_test.go

Previously was throwing on audio payloads. the codec's need to be mapped separately from video

Map audio codec type

---

cmd/server/grpc/main.go

Hack until renegotation is supported in pion. Force renegotation incase there are unmatched transceivers (i.e. sfu has more than one sender). We just naively create server offer. It is noop if things are already matched. We can remove once https://github.com/pion/webrtc/pull/1322 is merged

grpc renegotiate hack

---

README.md

The current link doesn't include the invite link or any info on how to get to it. 
The updated one is the same link that's used on the main pion/ion repo.
Might save the next person 10 minutes :)

Point Slack badge to Pion Slack info page

---

pkg/webrtctransport_test.go

For context, I'm debugging an issue where `peer.Close()` seems to hang.
Apparently it's not from just calling `.Close()`, but here's a free test. :)

Add test for peer.OnClose() listener.

---

pkg/router.go
pkg/router_test.go

Currently, `ReadRTP()` blocks the router from closing properly. This change prevents `ReadRTP()` from affecting the mutex.

Fix deadlock on Close().

---

cmd/server/grpc/main.go
cmd/server/json-rpc/main.go
go.sum
pkg/buffer.go
pkg/router.go
pkg/router_test.go
pkg/sender.go
pkg/session.go
pkg/session_test.go
pkg/sfu.go
pkg/sfu_test.go
pkg/transport.go
pkg/webrtctransport.go
pkg/webrtctransport_test.go

Updating api so transport is aware of the session it belongs to. This is necessary for relay but also simplifies things and makes it explicit that a peer can only belong to a single session at a time

Add session to transport

---

cmd/server/json-rpc/main.go

Send ICECandidate using `ToJSON()` rather than `String()`, same as in the grpc server. 
`ToJSON()` returns `sdpMLineIndex`  along with the `candidate` string, where as `String()` only returns the `candidate` string.

Send ICECandidate using ToJSON()

---

pkg/webrtctransport.go
pkg/webrtctransport_test.go

These are necessary so the biz node gets a signal when a new track is emitted to associate it with a uid and so the biz node can disconnect clients that end up in a terminal PeerConnectionState automatically.

Expose OnTrack and OnConnectionStateChange handlers.

---

.travis.yml
Makefile

updating travis so we can tag releases without pushing `latest` docker tag. since that will break ion

update ci, dont push docker latest for now

---

README.md
examples/pub-from-browser/jsfiddle/demo.js

This pull request addresses the following issues:
- The docker commands in the `README.md` file reference the wrong Dockerhub user `pion` instead of `pionwebrtc`. Therefore when you try to pull the image, you get the following error message: `docker: Error response from daemon: pull access denied for pion/ion-sfu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`.
- Typo in the `pub-from-browser` where the wrong name is used to reference the div. As a result the application throws an error when clicking on the `Start session` button.

Doc and example bug fixes

---

go.mod
go.sum

to prevent:
```
go: finding module for package google.golang.org/grpc/naming
/go/pkg/mod/google.golang.org/api@v0.13.0/internal/pool.go:10:2: module google.golang.org/grpc@latest found (v1.32.0), but does not contain package google.golang.org/grpc/naming
```

fix(deps): downgrade grpc

---

pkg/buffer.go

This changes helps to prevent cleaning of packets before being read in the nack pair calculation, this may happen when a video is muted and slow connections.
Fixes #122

Move cache cleaner after nack pair calculation

---

pkg/sender.go

Check for context done, to prevent writing on closed channel.
Fixes #141

Check for context done on Sender.receiveRTCP close #141

---

pkg/sender.go

@OrlandoCo given that this is a chrome issue, i decided to take the simple naive solution you suggested for now. hopefully this solves it so we dont need to add a complex solution and maybe chrome will fix it soon :)

fix(sender): delay sending rtp to avoid chrome issue 10139

---

pkg/receiver.go
pkg/sender.go

Since select statements can proceed in a pseudo-random selection, it's possible that runtime choose another case even if ctx.Done is called.
It's good practice to double check for context done that are in select, to prevent writing on closed channels.

chore(ctx): safe context done on channel writers

---

cmd/server/grpc/main.go
cmd/server/json-rpc/main.go
config.toml
pkg/log/log.go
pkg/sfu.go

Fix log print, make debug easy
before fix:
```
[2020-09-15 00:20:46.305] [INFO] [522][jsonrpc2.go][readMessages] => peer ckf2qhpv4000035183ouiyn68 join session test room
```
after fix:
```
[2020-09-14 23:47:23.773] [INFO] [186][main.go][Handle] => peer ckf2pasc80000fv18aq9qzuq5 join session test room
```
Fixes #...

fix log print by config

---

examples/pub-sub-in-browser/README.md

The command line flag `-p` has been changed to `-a`. The current startup command in the readme will lead to an error indicating that the flag is not valid.

Update  pub-sub-in-browser example readme

---

pkg/sender.go

Handle `io.ErrClosedPipe` more gracefully.
We should simplify how we are closing senders. It should be triggered by the `p.pc.RemoveTrack` call, rather than the other way around.

fix(sender): write on closed pipe err

---

config.toml
pkg/buffer.go
pkg/errors.go
pkg/receiver.go
pkg/receiver_test.go
pkg/router.go
pkg/router_test.go
pkg/sender.go
pkg/sender_test.go
pkg/session_test.go
pkg/sfu.go
pkg/sfu_test.go
pkg/webrtctransport.go
pkg/webrtctransport_test.go

This PR it's for simplify the relation between Receivers->Routers->Senders
-Receivers
1. Will close on  remote track removed or Close called.
2. Simplify to only have one single struct for video/audio. 
3. Errors are handled in receivers and not bubbled up.
-Routers
1. Routers will only fwd data between senders and receivers.
1. Routers will close themselves on receiver closed.
-Senders (TODO)
1. Senders will close on peer removed or track removed
2. Senders feedbacks will be directly forwarded and not calculated in SFU (Discussion required) and can be opted out.
Tests (TODO)
1. Make some minor changes to reflect these changes.
Breaking Changes:
None, so far the api reminds the same.
Fixes #177

feat(receivers): refactor receivers

---

pkg/receiver.go
pkg/receiver_test.go
pkg/sender.go
pkg/sender_test.go
pkg/simulcastsender.go
pkg/simulcastsender_test.go

This commit fix the case when publishers tracks where not removed from senders on disconnect, and senders where not removed from publishers on disconnect.

Fix close senders on publisher leave, and delete subs on leave

---

pkg/simplesender.go
pkg/simplesender_test.go
pkg/simulcastsender.go
pkg/simulcastsender_test.go

senders start by default is a muted state. the client can unmute when it is ready for the rtp

feat(senders): mute by default

---

examples/echotest/index.html

The variable `config` was assigned, but being used. 
In this example, as signaling process is being done via ion-sfu server, the `config` seems to serve no purpose.
If this was intended, sorry for bothering.
Fixes #252

Remove the config assignment not being used

---

pkg/router.go
pkg/webrtctransport.go

This pr tries to solve the issue of not senders starting once negotiated. Transceivers were used to get pending mids, instead parsing the sdp, to prevent getting wrong info from SDP and parsing it 2 times.

Fix sender start

---

config.toml
pkg/sfu.go
pkg/twcc_test.go

This PR add a memory ballast configurable through config file. The SFU consist on sending and receiving many packets at high rate that are being allocated in heap, this may cause many gc pause per minute. The ballast will increase the size of GC target, effectiveling reducing this pauses

feat(sfu): Add memory ballast

---

pkg/peer.go
pkg/session.go
pkg/sfu.go

- This breaks out the WebrtcTransportConfig from NewSFU - which allows other packages to create their own sfu implementation
- Abstracts peer to use TransportProvider interface (for passing in a customized sfu.SFU{})
- Fixes issue where the session onClose callback gets triggered twice

WebRTCTransportConfig Breakout, only call session.onClosed once

---

pkg/sfu/peer.go

reorder the function calls to register callbacks before calling set answer
Fixes #347

Fix for lost ice candidates

---

cmd/signal/json-rpc/server/server.go

The join before setting of the OnIceCandidate callback was causing an Ice candidate to not get sent in a very slim (1 out of 10) non deterministic manner.
I did not create an issue for this, but I can if you'd prefer. Its very similar to #347

Reorder calls to fix ice candidate not set when ice starts to trickle

---

README.md

Add instructions to the README on how to generate the protocol buffers and grpc code. I had to ask in Slack. It might be useful to others.
The docker based approach didn't work for me, so I also included instructions to do it without docker, the way I did.

Update README for protocol buffers generation instructions.

---

cmd/signal/grpc/server/server.go
cmd/signal/json-rpc/server/server.go
pkg/sfu/peer.go
pkg/sfu/sfu_test.go

Separate the offer sdp parameter in the peer.Join method.
This allows for a more flexible signal design. The current modification does not affect the existing ion-sfu signaling but separates the first offer SDP from the join method. When the join fails, we don’t have to operate pc or create an offer on the client-side.
before:
```go
answer, err := peer.Join(payload.Join.Sid, offer)
if err != nil {
switch err {
case sfu.ErrTransportExists:
...
}
```
after:
```go
err = peer.Join(payload.Join.Sid)
if err != nil {
switch err {
case sfu.ErrTransportExists:
return sig.SendReply(JoinReply{Success: false, Error: sfu.ErrTransportExists })
case sfu.RoomIsFull:
return sig.SendReply(JoinReply{Success: false, Error: sfu.RoomIsFull })
...
}
return sig.SendReply(JoinReply{Success: true, Error: nil }) …
```

Remove the offer sdp from peer.Join. fix #409

---

.github/workflows/docker-allrpc.yaml

Github workflow for automatically pushing allrpc Docker image similar to what already happens with [jsonrpc](https://github.com/pion/ion-sfu/blob/master/.github/workflows/docker-jsonrpc.yaml) and [grpc](https://github.com/pion/ion-sfu/blob/master/.github/workflows/docker-grpc.yaml).
Docker image will then be available as `pionwebrtc/ion-sfu:latest-allrpc` on Dockerhub.

Adding allrpc Github workflow

---

examples/pubsubtest/docker-compose.yaml

I was just made aware we provide this compose file in `pubsubtest` folder; if we use allrpc instead of jsonrpc, this makes a great entrypoint for introducing people to `ion-sdk-go`, `ion-avp` or `ion-app-flutter` (because jsonrpc is great for a simple pubsubtest, but everything else uses grpc)

fix: pubsubtest compose uses allrpc

---

pkg/sfu/peer.go
pkg/sfu/session.go

Add join configuration to peers that will allow to disable publishing or subscribing, this will allow other services or relaying to not open useless peerconnections.
The configuration is optional hence backwards compatible.

feat(sfu): add join config to peers

---

examples/pubsubtest/index.html
examples/pubsubtest/main.js

The 'pubsubtest' demo in its current form lacks audio from the remote elements. That's because the muted property on the video elements is true. We can only set muted to 'false' if the user has at least once interacted with the document, and hence usually a CTA like 'Enable Audio' or 'Join with Audio' is normally used.
More info: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
This PR implementes an 'Enable Audio' button that will enable audio for all the remote streams, present or future. 
PS: Refactored inline js code into a 'main.js' file.

Browser autoplay policy work around.

---

pkg/sfu/turn.go

Previously we tried to start a second tcp listener on `conf.Address`, which
gives error:
> listen tcp4 0.0.0.0:3478: bind: address already in use
Now we use the existing tcp listener and wrap it in a tls listener.

turn: Fix using TLS

---

pkg/sfu/downtrack.go

* receiver.DeleteDowntrack is re-entrant because receiver is calling writeRTP in downtrack
Fixes #...

Fix deadlock during layer switching in simulcast

---

examples/pubsubtest/main.js

Support `?session=myroom` and `?codec=h264` in pubsubtest parameters -- this examples gets used a lot in testing (and in the `pion/ion` project, the default room is "test room" rather than "test session"); it's convenient to be able to set these values on the fly without editing the file.

feat: pubsubtest parameters for session and codec

---

pkg/middlewares/datachannel/subscriberapi.go
pkg/sfu/downtrack.go
pkg/sfu/peer.go
pkg/sfu/session.go

* Allow publisher to select which layer(s) should be enabled. 
* Publisher can activate/deactivate layer with encoding params of the sender, however, there is no easy way to detect if a layer is enabled or not on sfu side. I added another message to middleware that will allow publishers to select which layer(s) are currently active on the sender side. It updates all the down tracks accordingly. 
* Message is then fanned out to all subscribers, so they are aware which layer is active and which ones are available. 
* In order to send messages on 'ion-sfu' channel (besides audio levels), I added a little bit more robust messaging type (similar to json-rpc). This is a breaking change for the client, unfortunately, but it gives us more flexibility if any new message type needs to be added in …

Simulcast: Allow layer selection for publisher

---

pkg/middlewares/datachannel/subscriberapi.go
pkg/sfu/peer.go

just small change to not make interface function for api only.

fix(sfu): make peer dc msg method not only for api

---

config.toml
pkg/sfu/sfu.go
pkg/sfu/sfu_test.go

Allows configuring `webrtc.SettingEngine` timeouts. Default values don't work for all cases. For example, during debug session, it would be great to increase timeouts to be able to stop client application in the debugger and keep connections opened to be able to resume.

feat(sfu): add webrtc timeouts config

---

cmd/signal/grpc/server/server.go
pkg/middlewares/datachannel/subscriberapi.go
pkg/relay/relay.go
pkg/sfu/errors.go
pkg/sfu/peer.go
pkg/sfu/publisher.go
pkg/sfu/sfu.go

This allow to use the relay in a way similar to the PeerConnections, also it added a Relay method in publishers, so a publisher can be relayed many times as requested. 
Now all the following negotiations are managed without intervention.

refactor(relay): make relay more compliant  to current workflow

---

pkg/sfu/peer.go
pkg/sfu/session.go

I receive this panic when adding a peer with `JoinConfig` `{ NoPublish: false, NoSubscribe: true }`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe30368]
goroutine 122 [running]:
github.com/pion/ion-sfu/pkg/sfu.(*Subscriber).AddDatachannel(0x0, 0x1381400, 0xc0001c0000, 0xc000358d50, 0xc0002aae00, 0xc000168840)
/go/pkg/mod/github.com/consumer/ion-sfu@v1.9.9-0.20210622161950-cffd0dbc3d4e/pkg/sfu/subscriber.go:75 +0x68
github.com/pion/ion-sfu/pkg/sfu.(*PeerLocal).Join(0xc0001c0000, 0xc0000a0150, 0x24, 0xc00022c780, 0x48, 0xc0001895b6, 0x1, 0x1, 0x0, 0xc000189610)
/go/pkg/mod/github.com/consumer/ion-sfu@v1.9.9-0.20210622161950-cffd0dbc3d4e/pkg/sfu/peer.go:150 +0x871
```

[fix] Add gate on conf.NoSubscribe before calling subscriber.AddDatachannel in PeerLocal join

---

pkg/buffer/helpers.go

Similar to the change made in Galene by jech, use SPS to detect keyframes. This fixes glitches in H.264 when layer switching
https://github.com/jech/galene/commit/4435a30a539a97c4dc2c062f19c6ff54b3930035

Use sequence parameter sets for h.264 keyframe detection

---

pkg/sfu/downtrack.go

RebaseTS will only allow to set offsets on first sync, causing issues on muting using API since TS and SN would be left in wrong state

fix(sfu): revert rebaseTS

---

go.sum
pkg/sfu/helpers.go
pkg/sfu/peer.go
pkg/sfu/publisher.go
pkg/sfu/session.go
pkg/sfu/sfu.go
pkg/sfu/subscriber.go

After network disruption, client may restart signaling with the same uid. It is possible that new AddPeer is called before RemovePeer in the exiting goroutine that delete the newly created one.
This fix also prevents duplicated NewSession in race condition. Also fixes GetSessions that the returned map is not thread-safe.

fix(sfu): remove race condition for session & peer

---

cmd/signal/grpc/server/server.go
pkg/sfu/downtrack.go
pkg/sfu/peer.go
pkg/sfu/publisher.go
pkg/sfu/router.go
pkg/sfu/subscriber.go

Do not subscribe to any stream during peer join, so that the application layer can perform fine control and subscribe on-demand
1, Listen publisher.OnPublishTrack event, generate StreamEvent and broadcast to each peer.
```go
peer.Publisher().OnPublisherTrack(func(track ion_sfu.PublisherTrack) {
log.Debugf("peer.OnPublisherTrack: \nKind %v, \nUid: %v,  \nMsid: %v,\nTrackID: %v",
track.Track.Kind(),
uid, 
track.Track.Msid(), 
track.Track.ID())
// event := &rtc.StreamEvent{.....}
// sig.BroadcastStreamEvent(event)
})
```
2,Peer uses the trackIds in StreamEvent to subscribe or unsubscribe.
```go
case *rtc.UpdateSettings_Subcription:
subscription := payload.UpdateSettings.GetSubcription()
enabled := subscription.GetSubscribe()
for _, trackId := range subscription.TrackIds {
if enabled {
// Add …
```

Add NoAutoSubscribe to peer.JoinConfig.

---

README.md

A path in the [ion-sdk-js](https://github.com/pion/ion-sdk-js) repository seems to have changed, and the README link is invalid.
Fixes #549

Fixed jsonrpc link in README

---

cmd/signal/grpc/server/server.go

The subscriber may be nil when fetching the peer.
Fixes #623

Fix subscriber nil dereferencing

---

README.md
examples/README.md

Some links weren't available due to renaming example directory (echotest -> echotest-jsonrpc).
Now they are available.

Fix broken links in READMEs

---

pkg/sfu/session.go

[FIX] When DataChannel Label already exists , The message of the new DC cannot be forwarded.
Fixes #...

[FIX]  Datachannle already exists

---

pkg/relay/relay.go
pkg/sfu/publisher.go

Hello my friend,
The ID in DataChannelParameters should be incremented, there are some problems with the current way of writing, it is 1 every time, I dealt with this problem, you can review it if you can.
At the same time, I found that relay does not process the Middleware Datachannel at present, so some functions implemented by ion-sfu datachannel cannot run properly under relay. I fixed this problem, and we can discuss it if necessary.

FIX: The creation of multiple relay datachannel failed. Procedure

---

cmd/signal/grpc/server/server.go
pkg/sfu/router.go

OnPublishTrack无法感知Track的动态增加与删除。在Router对象中增加Track的动态变化
OnPublishTrack cannot perceive the dynamic addition and deletion of Track. Increase the dynamic change of Track in the Router object
Fixes #...

通过 Router 对象感知 ReceiverTrack的Add与Remove

---

pkg/sfu/downtrack.go

If client sent rtcp.TransportLayerNack to audio downtrack,
ion-sfu going crash because downTrack.sequencer is only allocated for video track.
Check sequencer is nil when rtcp.TransportLayerNack has arrived.
Fixes #...

Fix crash when audio nack packets received

---

pkg/sfu/receiver.go

Currently after calling `WriteRTP` the code checks if the returned `err` is both an `io.EOF` and  an `io.ErrClosedPipe` this condition would never be satisfied & the down track would never be removed through this function
Fixes #...

Fix unreachable conditional in receiver's `writeRTP`

---

pkg/sfu/mediaengine.go

ion-sfu redefines mime types already present in webrtc/pion. This leads to some issues as it appears the parsing of the SDP for codecs is not entirely case-insensitive.
Fix #661

refactor: use mime types from webrtc/pion
