pion/ion-sfu

- go.mod
- go.sum
- pkg/node/internal.go
- pkg/rtc/transport/rtptransport.go
cuids are more suitable for storage in a db since the monotonically increasing. also the representation simplifies some logic (easier to convert between byte[]/string).
> use cuid rather than uuid

- config.toml
- pkg/node/internal.go
- pkg/node/publish.go
- pkg/node/subscribe.go
remove extra log line and remove options from proto input (since we are moving these to sdp)
> remove options + logging

- pkg/node/internal.go
- pkg/node/subscribe.go
- pkg/rtc/transport/webrtctransport.go
Also move rtc packet log to trace level.
> Fix crash on sub to unknown stream id

- examples/sub-to-browser/main.go
seems we need to use webrtc session description for the json unmarshal/marshal
> sub to browser fix

- examples/pub-from-browser/main.go
Fixes json.Unmarshall error while using sdp from browser for pub-from-browser example
Fixes #20
> Issue#23 FIXED

- cmd/server/json-rpc/main.go
- examples/README.md
- examples/pub-sub-in-browser/README.md
- examples/pub-sub-in-browser/demo.details
- examples/pub-sub-in-browser/jsfiddle/demo.details
- examples/pub-sub-in-browser/jsfiddle/demo.html
- examples/pub-sub-in-browser/jsfiddle/demo.js
Added a simple json-rpc interface and a pub-sub example. It is useful for testing
> json-rpc with example

- cmd/server/json-rpc/main.go
- go.mod
- pkg/media/engine.go
Since it is degrading pubs. Needs some work to fully support
> Disable transport cc for now

- pkg/router.go
- pkg/sender.go
Sender handles processing of send queue. Useful for simulcast senders
> Move send queue and loop to sender

- examples/pub-from-browser/README.md
- examples/pub-from-browser/main.go
- examples/pub-from-disk/README.md
- examples/pub-from-disk/main.go
- examples/sub-to-browser/README.md
- examples/sub-to-browser/main.go
> fix grpc example and doc

- pkg/log/log.go
> fix log printing asm_amd64.s

- pkg/receiver.go
- pkg/receiver_test.go
- pkg/router_test.go
- pkg/sfu.go
- pkg/sfu_test.go
- pkg/webrtctransport.go
Finish api suggestion updates
Closes #63
> Rename VideoReceiver, AudioReceiver

- go.mod
- go.sum
- pkg/receiver.go
- pkg/router.go
- pkg/sender.go
- pkg/track.go
- pkg/transport.go
- pkg/webrtctransport.go
necessary for supporting other transport types (i.e. rtptransport, quictransport)
> track interface

- .travis.yml
- Dockerfile
> build development docker

- go.sum
- pkg/router.go
> log track label

- .github/workflows/build-grpc.yaml
- .github/workflows/build-json-rpc.yaml
- .github/workflows/lint.yaml
- .travis.yml
- examples/pub-from-disk/main.go
- examples/sub-to-browser/main.go
- pkg/buffer.go
- pkg/receiver.go
- pkg/session_test.go
> ci(workflow): switch to github workflow

- .github/workflows/build-grpc.yaml
- .github/workflows/build-json-rpc.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- pkg/sender.go
> ci(triggers): update ci trigger rules

- pkg/webrtctransport_test.go
is that what you were thinking?
> fix(test): remove track race condition

- examples/pub-sub-in-browser/README.md
- examples/pub-sub-in-browser/jsfiddle/demo.js
add newly-received candidate to the browser's ICE
> add newly-received candidate to the browser's ICE

- config.toml
- pkg/mediaengine.go
- pkg/receiver.go
- pkg/receiver_test.go
- pkg/sfu.go
- pkg/webrtctransport_test.go
make recv-side-twcc work 
Fixes #117
> make recv-side-twcc work

- go.sum
> chore(deps): tidy

- pkg/webrtctransport.go
I wasn't able to reproduce https://github.com/pion/webrtc/issues/1343
> feat(tracks): enable remove track again

- config.toml
- pkg/buffer.go
- pkg/buffer_test.go
- pkg/receiver.go
- pkg/router.go
- pkg/router_test.go
- pkg/sender.go
- pkg/sender_test.go
- pkg/sfu.go
This pull requests it's to add more control over subs:
1. Add nack rate limit from subs to pubs
2. Enable/disable remb from subs to pubs
3. Subs should respect max bandwidth from SFU
> Add more control over senders

- pkg/receiver.go
- pkg/sfu.go
Fix a bad config name introduced in last commit
> fix(config): Fix config naming

- pkg/receiver.go
- pkg/router_test.go
- pkg/sender.go
- pkg/sfu.go
Remove unnecessary mutex in channels
> fix(mutex): Fix unnecessary mutex

- config.toml
- pkg/sfu.go
- pkg/sfu_test.go
> feat(ice): allow nat 1:1 configuration

- pkg/webrtctransport.go
we need to handle the case where ice candidates arrive before the negotiation completes
> fix(ice): buffer candidates if received before sdp negotiation completes

- cmd/server/grpc/main.go
- cmd/server/json-rpc/main.go
- examples/custom-signaling/main.go
- go.mod
- pkg/mediaengine.go
- pkg/mediaengine_test.go
- pkg/sfu.go
- pkg/webrtctransport.go
- pkg/webrtctransport_test.go
> Fix renegotiation issue where codecs where not registered

- pkg/receiver.go
- pkg/sender.go
Fix deadlock on senders closing
> Fix deadlock in senders closing

- examples/README.md
- Examples documentation has been invalid since the examples have been migrated to [ion-examples](https://github.com/pion/ion-examples) and are now fixed
Fixes #216
> Fixed examples documentation

- examples/echotest/index.html
Remove the lines from 172 to 191.
Fixes #231
> fix: Remove the duplication of addEventListener

- cmd/signal/grpc/main.go
- cmd/signal/json-rpc/main.go
> fix double printed help info

- examples/echotest/index.html
sorry for all the formatting changes, it was done automatically by prettier
> feat(example): use ion-sdk-js

- pkg/buffer.go
> Use not fixed remb implementation

- examples/pubsubtest/index.html
> feat(example): pubsub

- pkg/buffer.go
- pkg/packetqueue.go
- pkg/receiver.go
- pkg/simplesender.go
- pkg/simulcastsender.go
This PR solves the issue when many nacks blocks the buffer
> Fix nack locking buffer writes

- pkg/router.go
- pkg/simplesender.go
- pkg/simplesender_test.go
- pkg/simulcastsender.go
- pkg/simulcastsender_test.go
This PR fix the direction of the subs track to sendonly, and rate limit the pli request on join
> Fix sub transceiver direction and rate limit pli

- pkg/receiver.go
- pkg/simplesender.go
- pkg/simplesender_test.go
- pkg/simulcastsender.go
- pkg/simulcastsender_test.go
> Fix rate limit pli on receiver

- pkg/buffer.go
- pkg/receiver.go
- pkg/receiver_test.go
- pkg/router.go
- pkg/sfu.go
- pkg/simplesender.go
- pkg/simplesender_test.go
- pkg/simulcastsender.go
- pkg/simulcastsender_test.go
- pkg/webrtctransport.go
- pkg/webrtctransport_test.go
> Remove context

- pkg/webrtctransport.go
Close the peer connection only on ice closed state.
> fix(ice): close peer only on ice closed state

- pkg/router.go
- pkg/session.go
- pkg/sfu_test.go
- pkg/webrtctransport.go
Fix peers subscribing twice due to deferred initial subscription
> Fix subscribing twice

- pkg/peer.go
- pkg/sfu_test.go
> fix: concurrent test

- pkg/receiver.go
- pkg/simplesender.go
- pkg/simulcastsender.go
> feat(sfu): prevent write recent or future packets

- pkg/simplesender.go
- pkg/simulcastsender.go
> fix(sfu): copy headers

- pkg/peer.go
This PR will wait until answer is set after a negotiate, to run the next pending negotiation.
> fix(sfu): dont negotiate until answer received

- pkg/webrtctransport.go
> fix: close on ice fail

- go.mod
- go.sum
- pkg/buffer.go
- pkg/helpers.go
- pkg/packetqueue.go
- pkg/peer.go
- pkg/receiver.go
- pkg/router.go
- pkg/simplesender.go
- pkg/simulcastsender.go
- pkg/webrtctransport.go
> fix(buffer): fix packet buffer

- pkg/buffer.go
- pkg/router.go
- pkg/sender.go
- pkg/sfu.go
- pkg/simplesender.go
- pkg/simulcastsender.go
- pkg/webrtctransport.go
- pkg/webrtctransport_test.go
This PR includes the correct sdes mid headers on first packets
> fix(sfu): Include correct sdes mid headers

- examples/pubsubtest/index.html
- go.mod
- go.sum
- pkg/peer.go
- pkg/router.go
- pkg/sender.go
- pkg/sfu_test.go
- pkg/simplesender.go
- pkg/simplesender_test.go
- pkg/simulcastsender.go
- pkg/simulcastsender_test.go
- pkg/webrtctransport.go
Add locks in Peer, to avoid racings
> fix(sfu): Add locks in Peer

- cmd/signal/json-rpc/server/server.go
- examples/echotest/index.html
> feat: update sdk

- pkg/peer.go
- pkg/publisher.go
- pkg/session.go
Peer now subscribe on joins, is not required to wait for pub ice state
> fix: Dont subscribe on ice state

- pkg/nack.go
- pkg/simplesender.go
- pkg/simulcastsender.go
Fix an issue where retransmissions can be requested more than once.
Fixes #...
> fix(nack): fix nack retransmission throttling

- README.md
- config.toml
- examples/echotest/README.md
- examples/echotest/docker-compose.yaml
- examples/pubsubtest/README.md
- examples/pubsubtest/docker-compose.yaml
- examples/racetest/README.md
- examples/racetest/docker-compose.yaml
> feat(examples): improve docs + add docker compose

- pkg/buffer/buffer.go
- pkg/buffer/interceptor.go
- pkg/sfu/downtrack.go
- pkg/sfu/helpers_test.go
- pkg/sfu/router.go
- pkg/sfu/subscriber.go
> feat(SFU): add sender reports

- pkg/buffer/interceptor.go
- pkg/sfu/downtrack.go
- pkg/sfu/mediaengine.go
- pkg/sfu/router.go
- pkg/sfu/subscriber.go
Remove twcc congestion control for audio tracks to prevent lip sync issues.
> fix(sfu): remove audio tracks from twcc

- pkg/buffer/buffer.go
- pkg/buffer/interceptor.go
- pkg/sfu/nack.go
- pkg/sfu/subscriber.go
Fix buffer not requesting nack to peers
> fix(buffer): fix nack request

- README.md
some minor updates. please let me know if you have any suggestions on how we can improve docs
@OrlandoCo @robin-raymond @billylindeman @adwpc @Sean-Der @leewardbound @TannerGabriel
> chore(docs): add features + improve language

- examples/pubsubtest/index.html
Fixing some small mistakes in the `pubsubtest` example.
> Fixed small mistakes in pubsubtest application

- pkg/buffer/nack.go
simple change to avoid OOR error. Should be reviewed to ensure that the intended functionality is the result.
Fixes #350
> fix comparison in nack buffer

- cmd/signal/grpc/server/server.go
- go.sum
> fix(grpc): attach handlers before join

- config.toml
- go.sum
- pkg/sfu/router.go
- pkg/sfu/sfu.go
- pkg/stats/stream.go
> feat(metrics): add sfu metrics

- pkg/sfu/publisher.go
fix(sfu): Failed to load onICEConnectionStateChangeHandler
> fix(sfu): Failed to load onICEConnectionStateChangeHandler

- pkg/sfu/peer.go
- pkg/sfu/publisher.go
- pkg/sfu/subscriber.go
> fix(sfu): Fix ice logs

- config.toml
- go.mod
- pkg/sfu/sfu.go
- pkg/sfu/turn.go
> feat(turn): Add turn server

- pkg/buffer/bucket.go
- pkg/buffer/bucket_test.go
- pkg/buffer/buffer.go
- pkg/buffer/buffer_test.go
- pkg/buffer/factory.go
- pkg/buffer/nack.go
- pkg/buffer/nack_test.go
- pkg/sfu/router.go
- pkg/sfu/subscriber.go
Fix bucket pools to only store byte slices
> fix(buffer): Fix buckets pools

- pkg/sfu/peer.go
> fix: peer handler race

- cmd/signal/allrpc/main.go
- cmd/signal/allrpc/server/server.go
- cmd/signal/grpc/server/server.go
- config.toml
- examples/gallerytest/index.html
- examples/pubsubtest/index.html
- go.mod
- pkg/sfu/sfu.go
fix(pubsub html add multi player)
feat(allrpc add metrics)
fix(gallerytest html add muti player)
fix(Concurrency-grpc-stream-Send in different goroutines)
fix(open too many files error by setting ice.MulticastDNSModeDisabled)
Fixes #345 
Fixes #344
> fix-pubsub-allrpc

- pkg/sfu/datachannel.go
- pkg/sfu/session.go
- pkg/sfu/sfu.go
- pkg/sfu/subscriber.go
- pkg/sfu/turn.go
- Use WebrtcTransportConfig for init Session (exported type)
- Export InitTurnServer
- Export Datachannel.Label
- Auto init packet/buffer factories
-
Fixes #...
> Small tweaks for ion-cluster

- pkg/buffer/buffer.go
- pkg/sfu/peer.go
- pkg/sfu/session.go
Reduce locking on peer and session
> fix(peer): reduce peer/session locking

- pkg/sfu/downtrack.go
- pkg/sfu/subscriber.go
move reports generation into DownTrack, eliminating access to private vars
> move reports generation into DownTrack, eliminating access to private vars

- cmd/signal/json-rpc/server/server.go
- pkg/buffer/bucket.go
- pkg/buffer/bucket_test.go
- pkg/buffer/buffer.go
- pkg/buffer/nack.go
- pkg/buffer/nack_test.go
- pkg/sfu/sfu_test.go
Fix some issues with nack ext SN and moved outside bucket
> fix(nack): move nacker out of bucket

- cmd/signal/allrpc/Dockerfile
- cmd/signal/allrpc/main.go
Dockerfile for the `allrpc` version of `ion-sfu`. Command-line arguments for configuration can be provided using environment variables:
```bash
docker run -p 7000:7000 -p 8000:8000 -e gaddr=0.0.0.0:8000 -e jaddr=0.0.0.0:7000  allrpc
```
Fixes #440
> Added allrpc Dockerfile

- cmd/signal/allrpc/main.go
- cmd/signal/grpc/grpc-web/main.go
- cmd/signal/grpc/main.go
- cmd/signal/json-rpc/main.go
- config.toml
- pkg/sfu/sfu.go
- pkg/sfu/turn.go
It makes turn port range configurable
> make turn ports configurable

- pkg/middlewares/datachannel/README.md
Added a note about how to access the datachannels from the client end.
> Small tweak to middleware docs

- FAQ.md
- README.md
Linked it from the home page README. Three questions that I have asked, and so now know the answer to :-)
> Initial FAQ

- pkg/sfu/peer.go
- pkg/sfu/publisher.go
> fix logging peer id

- pkg/sfu/publisher.go
- pkg/sfu/receiver.go
- pkg/sfu/router.go
This will fix the case when late added simulcast layers will not reflex on remotes
> fix(sfu): will move layers as they arrive

- examples/pubsubtest/docker-compose.yaml
Loading the config file into the container and exposing the GRPC port.
> Pubsubtest docker-compose fixes

- cmd/signal/grpc/grpc-web/main.go
> feat(signal): add tls,cert,key flags to grpc-web

- pkg/sfu/sfu.go
Added convenient function to create SFU with turn with auth callback
> Added NewSFUWithTurnAuth function

- pkg/buffer/helpers.go
fix panic when vp8 unmarshal 
Fixes #478
> fix(sfu): panic when vp8 Unmarshal

- cmd/signal/grpc/server/server.go
> spelling mistake in new config settings

- pkg/relay/relay.go
- pkg/sfu/publisher.go
> feat(relay): add remote peers requests methods

- pkg/sfu/receiver.go
- pkg/sfu/session.go
Use user-configurable logger instead
> fix logger use

- pkg/buffer/buffer.go
> (fix) lock race

- README.md
Adding end to end solutions livekit/ion to guide users looking for such.
> Add other end to end projects that use ion-sfu
